-- =========================================================
-- Analysis 3: Product Performance
-- =========================================================
-- Objective:
-- Identify which products drive the most business value.

-- Business Definition:
-- "Product performance" = revenue generated by each product,
-- supported by demand (units sold) and category context.

-- Key Metrics:
-- total_revenue  = SUM(quantity * price)
-- total_quantity = SUM(quantity)

-- Tables Used:
-- order_items  → transactional data (product_id, quantity, price)
-- products     → product attributes (product_name, category)

-- Join Logic:
-- order_items.product_id = products.product_id

-- Granularity:
-- Aggregation at product level (GROUP BY product_id)

-- Steps:
-- 1. Start from order_items (source of revenue)
-- 2. Join products to attach name and category
-- 3. Compute revenue per row (quantity * price)
-- 4. Aggregate by product:
--      - SUM(quantity * price) → total_revenue
--      - SUM(quantity)         → total_quantity
-- 5. Sort by total_revenue DESC to rank best products

-- Output Columns:
-- product_id | product_name | category | total_revenue | total_quantity

-- Notes:
-- - GROUP BY includes all non-aggregated columns (product_id, product_name, category)
-- - ORDER BY revenue ensures top-performing products appear first
-- - total_quantity helps interpret demand alongside revenue
-- - ROUND() can be applied for presentation consistency

-- 1. Start from order_items
-- 2. Calculate revenue (quantity * price)
-- 3. Group by product_id
-- 4. Join with products to get product details
-- 5. Sum revenue and quantity
-- 6. Sort by total_revenue DESC

-- SELECT
--     Sum(quantity * price) AS revenue
--     o.product_id
--     p.product_id
--     p.product_name
--     p.category
-- from order_items o
-- INNER Join o.product_id = p.product_id
-- GROUP by 


SELECT
    o.product_id,
    p.product_name,
    p.category,
    ROUND(SUM(o.quantity * o.price), 2) AS total_revenue,
    SUM(o.quantity) AS total_quantity
FROM order_items o
JOIN products p
    ON o.product_id = p.product_id
GROUP BY
    o.product_id,
    p.product_name,
    p.category
ORDER BY total_revenue DESC;